#
# PRODUCTION
#
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitlabhq_production
  pool: 10
  username: git
  password: "secure password"
  # host: localhost
  # socket: /tmp/mysql.sock
